# Generated by Django 4.2.2 on 2023-06-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField()),
                ('name', models.CharField(max_length=200)),
                ('isbn', models.CharField()),
                ('page_count', models.IntegerField()),
                ('issued_out', models.BooleanField(default=False)),
                ('author', models.CharField()),
                ('year', models.CharField(max_length=4)),
                ('issuee', models.TextField(default='')),
                ('image', models.ImageField(null=True, upload_to='book_images/')),
                ('quantity', models.IntegerField(default=0)),
                ('slug', models.CharField(default='<django.db.models.fields.charfield>')),
                ('series', models.BooleanField(default=False)),
                ('name_of_series', models.CharField(null=True)),
                ('pos_in_series', models.IntegerField(null=True)),
                ('genre', models.TextField(default='')),
            ],
        ),
    ]
