# Generated by Django 4.2.2 on 2023-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_bookmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='issuee',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name_of_series',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='pos_in_series',
            field=models.IntegerField(blank=True),
        ),
    ]
