# Generated by Django 4.2.2 on 2023-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_requestbook_remove_bookmodel_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='issuee',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(default='What'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(upload_to='book_images/<'),
        ),
    ]
